// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_phi_and_update_tran
SEXP calc_phi_and_update_tran(SEXP waifw, SEXP state, SEXP s_indsR, SEXP i_indsR, SEXP exponentR, SEXP denomR, SEXP tran_matrix);
RcppExport SEXP _MRTransmissionModel_calc_phi_and_update_tran(SEXP waifwSEXP, SEXP stateSEXP, SEXP s_indsRSEXP, SEXP i_indsRSEXP, SEXP exponentRSEXP, SEXP denomRSEXP, SEXP tran_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type waifw(waifwSEXP);
    Rcpp::traits::input_parameter< SEXP >::type state(stateSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_indsR(s_indsRSEXP);
    Rcpp::traits::input_parameter< SEXP >::type i_indsR(i_indsRSEXP);
    Rcpp::traits::input_parameter< SEXP >::type exponentR(exponentRSEXP);
    Rcpp::traits::input_parameter< SEXP >::type denomR(denomRSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tran_matrix(tran_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_phi_and_update_tran(waifw, state, s_indsR, i_indsR, exponentR, denomR, tran_matrix));
    return rcpp_result_gen;
END_RCPP
}
// do_ID_transition_SIR_stochastic_moves_cl
SEXP do_ID_transition_SIR_stochastic_moves_cl(SEXP curstateR, SEXP transmatrixR);
RcppExport SEXP _MRTransmissionModel_do_ID_transition_SIR_stochastic_moves_cl(SEXP curstateRSEXP, SEXP transmatrixRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type curstateR(curstateRSEXP);
    Rcpp::traits::input_parameter< SEXP >::type transmatrixR(transmatrixRSEXP);
    rcpp_result_gen = Rcpp::wrap(do_ID_transition_SIR_stochastic_moves_cl(curstateR, transmatrixR));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _MRTransmissionModel_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// timesTwo
NumericVector timesTwo(NumericVector x);
RcppExport SEXP _MRTransmissionModel_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwo(x));
    return rcpp_result_gen;
END_RCPP
}
// update_age_surv_MSIRV
SEXP update_age_surv_MSIRV(SEXP age_surv_matrix, SEXP sz, SEXP age_spec_vacc_prob, SEXP v_indsR, SEXP m_indsR, SEXP s_indsR, SEXP i_indsR);
RcppExport SEXP _MRTransmissionModel_update_age_surv_MSIRV(SEXP age_surv_matrixSEXP, SEXP szSEXP, SEXP age_spec_vacc_probSEXP, SEXP v_indsRSEXP, SEXP m_indsRSEXP, SEXP s_indsRSEXP, SEXP i_indsRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type age_surv_matrix(age_surv_matrixSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sz(szSEXP);
    Rcpp::traits::input_parameter< SEXP >::type age_spec_vacc_prob(age_spec_vacc_probSEXP);
    Rcpp::traits::input_parameter< SEXP >::type v_indsR(v_indsRSEXP);
    Rcpp::traits::input_parameter< SEXP >::type m_indsR(m_indsRSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_indsR(s_indsRSEXP);
    Rcpp::traits::input_parameter< SEXP >::type i_indsR(i_indsRSEXP);
    rcpp_result_gen = Rcpp::wrap(update_age_surv_MSIRV(age_surv_matrix, sz, age_spec_vacc_prob, v_indsR, m_indsR, s_indsR, i_indsR));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP calc_phi_and_update_tran(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP do_ID_transition_SIR_stochastic_moves_cl(SEXP, SEXP);
RcppExport SEXP update_age_surv_MSIRV(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_MRTransmissionModel_calc_phi_and_update_tran", (DL_FUNC) &_MRTransmissionModel_calc_phi_and_update_tran, 7},
    {"_MRTransmissionModel_do_ID_transition_SIR_stochastic_moves_cl", (DL_FUNC) &_MRTransmissionModel_do_ID_transition_SIR_stochastic_moves_cl, 2},
    {"_MRTransmissionModel_rcpp_hello_world", (DL_FUNC) &_MRTransmissionModel_rcpp_hello_world, 0},
    {"_MRTransmissionModel_timesTwo", (DL_FUNC) &_MRTransmissionModel_timesTwo, 1},
    {"_MRTransmissionModel_update_age_surv_MSIRV", (DL_FUNC) &_MRTransmissionModel_update_age_surv_MSIRV, 7},
    {"calc_phi_and_update_tran",                 (DL_FUNC) &calc_phi_and_update_tran,                 7},
    {"do_ID_transition_SIR_stochastic_moves_cl", (DL_FUNC) &do_ID_transition_SIR_stochastic_moves_cl, 2},
    {"update_age_surv_MSIRV",                    (DL_FUNC) &update_age_surv_MSIRV,                    7},
    {NULL, NULL, 0}
};

RcppExport void R_init_MRTransmissionModel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
