# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Update transitions
#'
#' @param waifw who acquires immunity from whom matrix
#' @param state state
#' @param s_indsR something
#' @param i_indsR something
#' @param exponentR something
#' @param denomR something
#' @param tran_matrix transition matrix
#' @param N number of rows in transition matrix
#' @return transition matrix
calc_phi_and_update_tran <- function(waifw, state, s_indsR, i_indsR, exponentR, denomR, tran_matrix) {
    .Call('_MRTransmissionModel_calc_phi_and_update_tran', PACKAGE = 'MRTransmissionModel', waifw, state, s_indsR, i_indsR, exponentR, denomR, tran_matrix)
}

#' Make stochastic transition moves
#'
#' @param curstateR current state
#' @param transmatrixR transition matrix
#' @return something
do_ID_transition_SIR_stochastic_moves_cl <- function(curstateR, transmatrixR) {
    .Call('_MRTransmissionModel_do_ID_transition_SIR_stochastic_moves_cl', PACKAGE = 'MRTransmissionModel', curstateR, transmatrixR)
}

rcpp_hello_world <- function() {
    .Call('_MRTransmissionModel_rcpp_hello_world', PACKAGE = 'MRTransmissionModel')
}

#' Multiply by 2
#' 
#' @param x numeric vector
#' @return x times 2 
timesTwo <- function(x) {
    .Call('_MRTransmissionModel_timesTwo', PACKAGE = 'MRTransmissionModel', x)
}

#' Update age and survival matrix for MSIRV sims
#'
#' @param age_surv_matrix the matrix to update
#' @param sz something
#' @param age_spec_vacc_prob the age specific probability of vaccination
#' @param v_indsR index for vaccination
#' @param m_indsR index for maternal antibodies
#' @param s_indsR index for susceptibles
#' @param i_indsR index for infectious
#' @return something
update_age_surv_MSIRV <- function(age_surv_matrix, sz, age_spec_vacc_prob, v_indsR, m_indsR, s_indsR, i_indsR) {
    .Call('_MRTransmissionModel_update_age_surv_MSIRV', PACKAGE = 'MRTransmissionModel', age_surv_matrix, sz, age_spec_vacc_prob, v_indsR, m_indsR, s_indsR, i_indsR)
}

